# Generated by Django 5.0.3 on 2024-03-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtimes.cinema', unique=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielist.movie', unique=True),
        ),
    ]
