# Generated by Django 5.0.3 on 2024-03-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0003_alter_screening_cinema_alter_screening_movie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='screening',
            unique_together=set(),
        ),
    ]
